// Vintage computer product catalog
export const categories = [
  { id: 'all', label: 'All' },
  { id: 'apple', label: 'Apple' },
  { id: 'commodore', label: 'Commodore' },
  { id: 'atari', label: 'Atari' },
  { id: 'ibm', label: 'IBM & Clones' },
  { id: 'parts', label: 'Parts' },
]

export const products = [
  {
    id: 'amiga-500',
    name: 'Commodore Amiga 500',
    eyebrow: 'Commodore · 1987',
    desc: 'The legendary home computer with custom co-processors and 4096 colors. Tested, recapped, with original PSU.',
    price: 349,
    oldPrice: 449,
    category: 'commodore',
    tag: 'hot',
    color: { case: '#c4c8d0', accent: '#ffb347', screen: '#00f0ff' },
    type: 'a500',
  },
  {
    id: 'mac-se30',
    name: 'Apple Macintosh SE/30',
    eyebrow: 'Apple · 1989',
    desc: 'Compact Mac with 9" b&w CRT. Recently serviced logic board, new caps, working floppy.',
    price: 899,
    category: 'apple',
    tag: 'refurb',
    color: { case: '#e6e6e6', accent: '#b6ff5e', screen: '#b6ff5e' },
    type: 'macse',
  },
  {
    id: 'c64',
    name: 'Commodore 64 — Breadbin',
    eyebrow: 'Commodore · 1982',
    desc: 'The best-selling single computer model of all time. Fully recapped, working SID 6581 sound chip.',
    price: 219,
    category: 'commodore',
    tag: 'new',
    color: { case: '#b8a07a', accent: '#3a4a8a', screen: '#7df0ff' },
    type: 'c64',
  },
  {
    id: 'atari-st',
    name: 'Atari 1040 STf',
    eyebrow: 'Atari · 1986',
    desc: 'MIDI-equipped powerhouse with 1MB RAM. Perfect for musicians and retro enthusiasts.',
    price: 379,
    oldPrice: 499,
    category: 'atari',
    tag: 'hot',
    color: { case: '#d4d4d4', accent: '#ff6ec7', screen: '#ff6ec7' },
    type: 'atarist',
  },
  {
    id: 'ibm-pp',
    name: 'IBM PS/2 Model 25',
    eyebrow: 'IBM · 1987',
    desc: 'Compact all-in-one PC with VGA. VGA output, original IBM keyboard and mouse included.',
    price: 459,
    category: 'ibm',
    tag: 'refurb',
    color: { case: '#dadbdf', accent: '#1a1a22', screen: '#00f0ff' },
    type: 'ibm',
  },
  {
    id: 'apple-iigs',
    name: 'Apple IIGS "Woz Limited"',
    eyebrow: 'Apple · 1986',
    desc: 'ROM 03 · 1MB RAM · Ensoniq sound. The most powerful 8-bit Apple ever made.',
    price: 1299,
    category: 'apple',
    tag: 'new',
    color: { case: '#f0f0f2', accent: '#ff2bd6', screen: '#ff2bd6' },
    type: 'iigs',
  },
  {
    id: 'amiga-1200',
    name: 'Commodore Amiga 1200',
    eyebrow: 'Commodore · 1992',
    desc: 'AGA chipset, 2MB chip RAM, PCMCIA port. The last 68k Amiga. Indestructible build quality.',
    price: 549,
    oldPrice: 699,
    category: 'commodore',
    tag: 'hot',
    color: { case: '#d8d8d8', accent: '#ffb347', screen: '#b6ff5e' },
    type: 'a1200',
  },
  {
    id: 'c128',
    name: 'Commodore 128D',
    eyebrow: 'Commodore · 1985',
    desc: 'Triple-mode: C64, C128, Z80 CP/M. Real metal case version. The ultimate C64 companion.',
    price: 459,
    category: 'commodore',
    tag: 'refurb',
    color: { case: '#c8c8c8', accent: '#3a4a8a', screen: '#7df0ff' },
    type: 'c128',
  },
]

export const timeline = [
  { year: '1977', name: 'Apple II', desc: 'Color graphics, BASIC in ROM, the first mass-market personal computer.' },
  { year: '1981', name: 'IBM PC 5150', desc: 'The architecture that conquered business. Anything compatible was an "IBM PC".' },
  { year: '1982', name: 'Commodore 64', desc: '17 million units sold. The number remains unbeaten for a single computer model.' },
  { year: '1984', name: 'Macintosh 128K', desc: 'The friendly face of computing. WIMP interface, mouse, 9" black & white CRT.' },
  { year: '1985', name: 'Amiga 1000', desc: '4-channel stereo, 4096 colors, custom co-processors. Years ahead of its time.' },
  { year: '1989', name: 'Macintosh SE/30', desc: '4MB RAM in a compact Mac. Still used today as a classic print server.' },
]

export const reviews = [
  {
    name: 'Luca R.',
    role: 'Vintage collector · Milano',
    rating: 5,
    text: 'My Amiga 500 arrived perfectly packed. Recapping job is pristine, and the original PSU is in incredible shape. I have bought from 4 different shops and RETROBAY is by far the most careful.',
  },
  {
    name: 'Sarah K.',
    role: 'Synth musician · Berlin',
    rating: 5,
    text: 'The Atari 1040 STf with MIDI is the heart of my home studio now. Tested everything, sent a video of the unit running before shipping. Trustworthy.',
  },
  {
    name: 'Marco T.',
    role: 'Retro museum curator',
    rating: 5,
    text: 'We sourced 12 machines for a new exhibit. Every single one came with provenance docs and a recap certificate. The C128D is museum-quality.',
  },
]
